### ISSUE TITLE
var

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/js-dom1#1]
https://github.com/DenisPitsul/js-dom1/blob/b5fe30056ec0437be548a4d509597dea12137839/assets/js/index.js#L32
- використання `var` в комерційному коді є поганим стилем у зв'язку з недоліками і відповідними потенційними проблемами порівняно з `let`/`const`

**Comment by DenisPitsul** [comment]
Fixed in commit:
https://github.com/DenisPitsul/js-dom1/commit/58d28e2c1f92caa1cbde2c0311c0c42f11fb64d0
